export const partners = [
  {
    name: "Patanjali",
    logoSrc: "/assets/distributor-img/partners/patanjali.png",
    width: 214,
    height: 60,
    category: "Ghee, Oils & Staples",
    subcategory: "Food, Oil and Biscuits",
    coverSrc: "/assets/distributor-img/partners/patanjali.jpg",
    description:
      "Founded in 2006, Patanjali deals in Ayurvedic products, food items, and healthcare solutions. It has become one of the largest brands in the FMCG sector in India, promoting swadeshi products.  The brand offers a wide range of food products, edible oils, and biscuits across Indian households.",
  },
  {
    name: "Britannia",
    logoSrc: "/assets/distributor-img/partners/britania.png",
    width: 168,
    height: 60,
    category: "Foods & Beverages",
    subcategory: "Biscuits & Snacks",
    coverSrc: "/assets/distributor-img/partners/britania.jpg",
    description:
      "Established in 1892, Britannia deals in biscuits, dairy products, cakes, and breads. It is one of India’s most trusted food brands with a strong legacy and market leadership in the biscuit segment. Its popular products include Good Day, Marie Gold, Bourbon, Little Hearts, and NutriChoice.",
  },
  {
    name: "Keya",
    logoSrc: "/assets/distributor-img/partners/keya.png",
    width: 112,
    height: 60,
    category: "Spices & Seasonings",
    subcategory: "Spices & herbs",
    coverSrc: "/assets/distributor-img/partners/keya.jpg",
    description:
      "Established in 2009, Keya deals in premium herbs, spices, seasonings, and condiments. It is known for introducing international-quality seasonings to Indian kitchens. The brand is popular for oregano, chilli flakes, mixed herbs, pasta seasoning, and spice grinders.",
  },
  {
    name: "SuperYou",
    logoSrc: "/assets/distributor-img/partners/superyou.svg",
    width: 160,
    height: 50,
    maxHeight: 50,
    category: "Health & Nutrition",
    subcategory: "Protein Snacks & Wafers",
    coverSrc: "/assets/distributor-img/partners/superyou.jpg",
    websiteUrl: "https://superyou.in/",
    description:
      "Founded in 2024 by actor Ranveer Singh and Nikunj Biyani, SuperYou deals in protein-packed wafers, nutrition bars, and health snacks. Designed for active lifestyles, the brand offers high-protein, fiber-rich treats crafted with zero added sugar.",
  },
  {
    name: "Reckitt",
    logoSrc: "/assets/distributor-img/partners/Reckitt_logo.svg.webp",
    width: 160,
    height: 55,
    maxHeight: 55,
    category: "Hygiene, Health & Home",
    subcategory: "Hygiene & Personal Care",
    coverSrc: "/assets/distributor-img/partners/reckitt-partners.png",
    websiteUrl: "https://www.reckitt.com/",
    description:
      "Established in 1819, Reckitt is a global FMCG leader dealing in health, hygiene, and nutrition solutions. Trusted across households worldwide, its iconic brand portfolio includes Dettol, Lysol, Harpic, Strepsils, Vanish, and Veet.",
  },
  {
    name: "Wipro",
    logoSrc: "/assets/distributor-img/partners/wipro.png",
    width: 76,
    height: 60,
    category: "Personal & Home Care",
    subcategory: "Soaps, Skincare & Hygiene",
    coverSrc: "/assets/distributor-img/partners/wipro.jpg",
    description:
      "Established in 1945, Wipro Consumer Care offers trusted personal care and hygiene products, including popular brands. The brand is known for its soaps, skincare, and hygiene products that cater to a wide range of consumer needs.",
    maxHeight: 72,
  },
  {
    name: "Bansuri",
    logoSrc: "/assets/distributor-img/partners/bansuri.png",
    width: 94,
    height: 72,
    category: "FMCG & Fragrance",
    subcategory: "Incense & Fragrance",
    coverSrc: "/assets/distributor-img/partners/bansuri.jpg",
    description:
      "Established under NR Group (founded 1948), Bansuri deals in traditional fragrances, incense sticks, and spiritual care products associated with Cycle Pure. It offers culturally inspired aromatic products designed for daily pooja, meditation, and spiritual environments, reflecting India’s fragrance heritage.",
    maxHeight: 720,
  },
  {
    name: "Sundrop",
    logoSrc: "/assets/distributor-img/partners/sundrop.png",
    width: 86,
    height: 72,
    category: "FMCG & Food Products",
    subcategory: "Edible Oils & Food Staples",
    coverSrc: "/assets/distributor-img/partners/sundrop.jpg",
    description:
      "Established in 1989, Sundrop Brands deals in edible oils, peanut butter, spreads, and breakfast essentials. Known for quality and nutrition, Sundrop is widely used across Indian households for everyday healthy cooking and food preparation.",
    maxHeight: 720,
  },
  {
    name: "Tata Consumer Products",
    logoSrc: "/assets/distributor-img/partners/tata_logo.png",
    width: 250,
    height: 50,
    category: "FMCG",
    subcategory: "Beverages & Foods",
    coverSrc: "/assets/distributor-img/partners/tata-cover.jpg",
    websiteUrl: "https://www.tataconsumer.com/",
    className: "rounded-md",
    description:
      "Established in 1962, Tata Consumer Products deals in tea, coffee, water, salt, pulses, spices, and ready-to-cook offerings. It is a focused consumer products company uniting the principal food and beverage interests of the Tata Group under one umbrella.",
  },
];
