import { Montserrat, Merriweather } from "next/font/google";

import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

// Configure fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700", "800"], // Regular, Bold, ExtraBold
  variable: "--font-montserrat",
  display: "swap",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["700"], // Bold only (for subheads)
  variable: "--font-merriweather",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Homestead Experts - Medical Expert Witness Services</title>

        {/* favicons */}
        <link
          rel="icon"
          sizes="180x180"
          href="/assets/images/favicons/favicon_180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/assets/images/favicons/favicon_180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/assets/images/favicons/favicon_180x180.png"
        />
        <link rel="manifest" href="/assets/images/favicons/site.webmanifest" />

        <meta
          name="description"
          content="Homestead Experts provides trusted medical expert witness services, connecting legal teams with certified specialists across all medical fields."
        />

        {/* vendor CSS */}
        <link
          rel="stylesheet"
          href="/assets/vendors/bootstrap/css/bootstrap.min.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/bootstrap-select/bootstrap-select.min.css"
        />
        <link rel="stylesheet" href="/assets/vendors/animate/animate.min.css" />
        <link
          rel="stylesheet"
          href="/assets/vendors/fontawesome/css/all.min.css"
        />
        <link rel="stylesheet" href="/assets/vendors/jquery-ui/jquery-ui.css" />
        <link rel="stylesheet" href="/assets/vendors/jarallax/jarallax.css" />
        <link
          rel="stylesheet"
          href="/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/nouislider/nouislider.min.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/nouislider/nouislider.pips.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/tiny-slider/tiny-slider.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/procounsel-icons/style.css"
        />
        <link rel="stylesheet" href="/assets/vendors/slick/slick.css" />
        <link
          rel="stylesheet"
          href="/assets/vendors/owl-carousel/css/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/owl-carousel/css/owl.theme.default.min.css"
        />

        {/* template styles */}
        <link rel="stylesheet" href="/assets/css/procounsel-dark.css" />
        <link rel="stylesheet" href="/assets/css/procounsel.css" />
      </head>
      <body
        className={`${montserrat.variable} ${merriweather.variable} custom-cursor`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
